services:
  postgres:
    image: postgres:15
    container_name: my_postgres_todo
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # données persistantes

volumes:
  postgres_data:
